#!/usr/bin/env python

from argparse import ArgumentParser
from pathlib import Path

from data_folder_types import *

parser = ArgumentParser(
    prog='recursive_enumeration',
    description='Parse all subfolders of the current data folder and print their type')

args = parser.parse_args()

root_folder = root()
root_folder.enumerate_children(False)