#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser

from data_folder_types import *

parser = ArgumentParser(
    prog='HexBox',
    description='https://github.com/cg3hci/HexBox')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder',
    required=True)

args = parser.parse_args()

input = AbstractDataFolder.instantiate(Path(args.input))
input.HexBox()