#!/usr/bin/env python

from argparse import ArgumentParser

from sys import path
path.append('../') # required for relative import without package
from HexMeshWorkshop import *

parser = ArgumentParser(
    prog='import_MAMBO',
    description='Import MAMBO dataset in the data folder')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the MAMBO folder',
    required=False)

args = parser.parse_args()

root_folder = root()
root_folder.import_MAMBO(args.input)