#!/usr/bin/env python

from settings import *
from collection_manager import *

# TODO move to a root data folder method

collections_manager = CollectionsManager(Settings.path('data_folder'))
for collection in collections_manager.collections():
    print(collection)