#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser

from data_folder_types import *

parser = ArgumentParser(
    prog='polycube_withHexEx',
    description='Simple polycube parametrization for libHexEx')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type labeling)',
    required=True)

parser.add_argument(
    '--scale',
    dest='scale',
    metavar='FLOAT',
    help='scaling factor applied before libHexEx. higher = more hexahedra',
    default='1.0')

parser.add_argument(
    '--keep-debug-files',
    action='store_true',
    dest='keep_debug_files',
    help='if the debug .geogram files should be kept')

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the output at the end')

args = parser.parse_args()

cm = CollectionsManager(Settings.path('data_folder'))

if args.input in cm.collections():
    print('input is a colleciton -> batch mode')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
subfolder = input.polycube_withHexEx(args.scale,args.keep_debug_files)

if args.view_output:
    hexmesh_folder = AbstractDataFolder.instantiate(subfolder)
    hexmesh_folder.view()