#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser

from sys import path
path.append('../') # required for relative import without package
from HexMeshWorkshop import *

parser = ArgumentParser(
    prog='preprocess_polycube',
    description='Pre-process a tet-mesh so that the interior may not have impossible configuration for a given labeling')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type labeling)',
    required=True)

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the output at the end')

args = parser.parse_args()

cm = CollectionsManager(Settings.path('data_folder'))

if args.input in cm.collections():
    print('input is a colleciton -> batch mode')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
input.preprocess_polycube()

if args.view_output:
    input.view(what='preprocessed_polycube')