#!/usr/bin/env python

from argparse import ArgumentParser
from pathlib import Path

from data_folder_types import *

parser = ArgumentParser(
    prog='print_history',
    description='Print the date and name of algorithms applied for the input folder')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input data folder',
    required=True)

args = parser.parse_args()

input_folder = AbstractDataFolder.instantiate(args.input)
input_folder.print_history()