#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser

from data_folder_types import *

parser = ArgumentParser(
    prog='mesh_stats',
    description='Print mesh stats (over vertices, facets, etc) of a tetrahedral mesh')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type tet_mesh)',
    required=True)

args = parser.parse_args()

input = AbstractDataFolder.instantiate(Path(args.input))
mesh_stats_dict = input.get_mesh_stats_dict()
print(mesh_stats_dict)