#!/usr/bin/python

from pathlib import Path
from argparse import ArgumentParser

from sys import path
path.append('../') # required for relative import without package
from HexMeshWorkshop import *

parser = ArgumentParser(
    prog='typeof',
    description='Print the type of the given data folder')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder',
    required=True)

args = parser.parse_args()

input = AbstractDataFolder.instantiate(Path(args.input))
print(input.type())