#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
path.append(str(Path(__file__).parent.parent.absolute()))

from modules.data_folder_types import *

parser = ArgumentParser(
    prog='view',
    description='View the content of a subfolder')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder',
    required=True)

parser.add_argument(
    '--what',
    dest='what',
    metavar='STRING',
    help='specify a kind of visualization (depends on the folder type)',
    required=False)

args = parser.parse_args()

input = AbstractDataFolder.instantiate(Path(args.input))
input.view(what=args.what)