#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser

from sys import path
path.append('../') # required for relative import without package
from HexMeshWorkshop import *

parser = ArgumentParser(
    prog='volume_labeling',
    description='Compute the volume labeling (per cell facet) from the surface labeling (per surface triangle)')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type labeling)',
    required=True)

args = parser.parse_args()

cm = CollectionsManager(Settings.path('data_folder'))

if args.input in cm.collections():
    print('input is a colleciton -> batch mode')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
input.volume_labeling()

# no --view option because there is no visualization mode/tool for volume labelings