#!/usr/bin/python

from sys import path
path.append('../') # required for relative import without package

from HexMeshWorkshop import *

db = HexMeshWorkshopDatabase()
db.clear_database_and_datafiles()
