#!/usr/bin/python

from pathlib import Path
from argparse import ArgumentParser

from sys import path
path.append('../') # required for relative import without package
from HexMeshWorkshop import *

parser = ArgumentParser(
    prog='Gmsh',
    description='Tetrahedrization with Gmsh')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder',
    required=True)

parser.add_argument(
    '--mesh-size',
    dest='mesh_size',
    metavar='REAL',
    help='element size factor in ]0,1] (default is 0.05)',
    required=False,
    default=0.05)

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the output at the end')

args = parser.parse_args()

cm = CollectionsManager(Path.expanduser(Path(load(open('../settings.json'))['data_folder'])))

if args.input in cm.collections():
    print('input is a colleciton -> batch mode')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
subfolder = input.Gmsh(float(args.mesh_size))

mesh_folder = AbstractDataFolder.instantiate(subfolder)
mesh_folder.extract_surface()

if args.view_output:
    mesh_folder.view()