#!/usr/bin/python

from argparse import ArgumentParser

from sys import path
path.append('../') # required for relative import without package
from HexMeshWorkshop import *

parser = ArgumentParser(
    prog='import_step',
    description='Import a step file in the data folder')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the MAMBO folder',
    required=False)

args = parser.parse_args()

data_folder = get_datafolder()

input = Path(args.input)
assert(input.exists())
step_object = step(data_folder / input.stem, input)
print(input.stem + ' imported')
# TODO allow to append to a collection