#!/usr/bin/python

from sys import path
path.append('../') # required for relative import without package
from HexMeshWorkshop import *

# TODO move to a root data folder method

collections_manager = CollectionsManager(Settings.data_folder())
for collection in collections_manager.collections():
    print(collection)