#!/usr/bin/python

from pathlib import Path
from argparse import ArgumentParser

from sys import path
path.append('../') # required for relative import without package
from HexMeshWorkshop import *

parser = ArgumentParser(
    prog='robustPolycube',
    description='https://github.com/fprotais/robustPolycube')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type labeling)',
    required=True)

parser.add_argument(
    '--elem-sizing',
    dest='element_sizing',
    metavar='FLOAT',
    help='element sizing: ratio compared to the input mesh edge size. smaller = more hexahedra',
    default='1.0')

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the output at the end')

args = parser.parse_args()

cm = CollectionsManager(Settings.path('data_folder'))

if args.input in cm.collections():
    print('input is a colleciton -> batch mode')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
input.rb_generate_deformation()
subfolder = input.rb_generate_quantization(args.element_sizing)

if args.view_output:
    subfolder.view()