#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from rich.pretty import pprint
from sys import path
path.append(str(Path(__file__).parent.parent.absolute()))

from modules.collection_manager import *

parser = ArgumentParser(
    prog='datafolder',
    description='Collections management (interface to collections.json)')

parser.add_argument(
    'action',
    choices=['print'])

# TODO move actions code to root data folder methods

cm = CollectionsManager()
for collection_name in cm.collections_names():
    print(collection_name)