#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
from rich.console import Console
from rich.traceback import install

# Add root of HexMeshWorkshop project folder in path
project_root = str(Path(__file__).parent.parent.absolute())
if path[-1] != project_root: path.append(project_root)

# colored and detailed Python traceback
install(show_locals=True,width=Console().width,word_wrap=True)

# own modules
from modules.data_folder_types import *

parser = ArgumentParser(
    prog='datafolder',
    description='Collections management (interface to collections.json)')

parser.add_argument(
    'action',
    choices=['print'])

root_folder = root()
root_folder.view(what='collections')

print('')

# verbose print
for collection in root_folder.collections_manager.collections.values():
    print(collection)

print('')

# test gather_all_folders()
for name,collection in root_folder.collections_manager.collections.items():
    print(name)
    print(collection.gather_all_folders(root_folder.collections_manager.collections))
    print('')