#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from rich.pretty import pprint
from sys import path
path.append(str(Path(__file__).parent.parent.absolute()))

from modules.data_folder_types import *

parser = ArgumentParser(
    prog='datafolder',
    description='Collections management (interface to collections.json)')

parser.add_argument(
    'action',
    choices=['print'])

root_folder = root()
root_folder.view(what='collections')