#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
from rich.console import Console
from rich.traceback import install

# Add root of HexMeshWorkshop project folder in path
project_root = str(Path(__file__).parent.parent.absolute())
if path[-1] != project_root: path.append(project_root)

# colored and detailed Python traceback
install(show_locals=True,width=Console().width,word_wrap=True)

# own modules
from modules.data_folder_types import *

parser = ArgumentParser(
    prog='generate_report',
    description='Generate an execution report from the data folder content')

args = parser.parse_args()

root_folder = root()
root_folder.generate_report()