#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
from rich.console import Console
from rich.traceback import install

# Add root of HexMeshWorkshop project folder in path
project_root = str(Path(__file__).parent.parent.absolute())
if path[-1] != project_root: path.append(project_root)

# colored and detailed Python traceback
install(show_locals=True,width=Console().width,word_wrap=True)

# own modules
from modules.data_folder_types import *

parser = ArgumentParser(
    prog='Gmsh',
    description='Tetrahedrization with Gmsh')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder',
    required=True)

parser.add_argument(
    '--mesh-size',
    dest='mesh_size',
    metavar='REAL',
    help='element size factor in ]0,1] (default is 0.05)',
    required=False,
    default=0.05)

parser.add_argument(
    '-nt','--nb-threads',
    dest='nb_threads',
    metavar='INT',
    help='number of threads',
    required=False,
    default=8)

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the output at the end')

args = parser.parse_args()

input = AbstractDataFolder.instantiate(Path(args.input))
subfolder = input.Gmsh(float(args.mesh_size),int(args.nb_threads))

mesh_folder = AbstractDataFolder.instantiate(subfolder)
mesh_folder.extract_surface()

if args.view_output:
    mesh_folder.view()