#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
from rich.console import Console
from rich.traceback import install

# Add root of HexMeshWorkshop project folder in path
project_root = str(Path(__file__).parent.parent.absolute())
if path[-1] != project_root: path.append(project_root)

# colored and detailed Python traceback
install(show_locals=True,width=Console().width,word_wrap=True)

# own modules
from modules.data_folder_types import *

parser = ArgumentParser(
    prog='import_step',
    description='Import a step file in the data folder')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the STEP file to import',
    required=False)

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the imported STEP file at the end')

args = parser.parse_args()

input = Path(args.input)
assert(input.exists())
step_object = step(Settings.path('data_folder') / input.stem, input)
print(input.stem + ' imported')
# TODO allow to append to a collection

if args.view_output:
    step_object.view()