#!/usr/bin/env python

from modules.settings import *
from modules.collection_manager import *
from sys import path
path.append(str(Path(__file__).parent.parent.absolute()))

# TODO move to a root data folder method

collections_manager = CollectionsManager(Settings.path('data_folder'))
for collection in collections_manager.collections():
    print(collection)