#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
from rich.console import Console
from rich.traceback import install

# Add root of HexMeshWorkshop project folder in path
project_root = str(Path(__file__).parent.parent.absolute())
if path[-1] != project_root: path.append(project_root)

# colored and detailed Python traceback
install(show_locals=True,width=Console().width,word_wrap=True)

# own modules
from modules.data_folder_types import *

parser = ArgumentParser(
    prog='marchinghex',
    description='https://github.com/fprotais/marchinghex')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type tet_mesh)',
    required=True)

parser.add_argument(
    '--scale',
    dest='scale',
    metavar='FLOAT',
    help='scale of the grid. 5 is very fine grid, 0.1 is very coarse.',
    default='1.0')

parser.add_argument(
    '--keep-debug-files',
    action='store_true',
    dest='keep_debug_files',
    help='if the debug mesh files should be kept')

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the output at the end')

args = parser.parse_args()

root_folder = root()
if args.input in root_folder.collections_manager.collections_names():
    print('input is a collection -> batch mode')
    print('NOT IMPLEMENTED')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
subfolder = input.marchinghex(args.scale,args.keep_debug_files)

if args.view_output:
    hexmesh_folder = AbstractDataFolder.instantiate(subfolder)
    hexmesh_folder.view()