#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
path.append(str(Path(__file__).parent.parent.absolute()))

from modules.data_folder_types import *

parser = ArgumentParser(
    prog='naive_labeling',
    description='Generate the naive labeling of a tet_mesh data folder')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input data folder (type tet_mesh)',
    required=True)

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the output at the end')

args = parser.parse_args()

root_folder = root()
if args.input in root_folder.collections_manager.collections_names():
    print('input is a collection -> batch mode')
    print('NOT IMPLEMENTED')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
subfolder = input.naive_labeling()

if args.view_output:
    labeling_folder = AbstractDataFolder.instantiate(subfolder)
    labeling_folder.view()