#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
from rich.console import Console
from rich.traceback import install

# Add root of HexMeshWorkshop project folder in path
project_root = str(Path(__file__).parent.parent.absolute())
if path[-1] != project_root: path.append(project_root)

# colored and detailed Python traceback
install(show_locals=True,width=Console().width,word_wrap=True)

# own modules
from modules.data_folder_types import *

parser = ArgumentParser(
    prog='preprocess_polycube',
    description='Pre-process a tet-mesh so that the interior may not have impossible configuration for a given labeling')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type labeling)',
    required=True)

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the output at the end')

args = parser.parse_args()

input = AbstractDataFolder.instantiate(Path(args.input))
input.preprocess_polycube()

if args.view_output:
    input.view(what='preprocessed_polycube')