#!/usr/bin/env python

from argparse import ArgumentParser
from pathlib import Path
from sys import path
from rich.console import Console
from rich.traceback import install

# Add root of HexMeshWorkshop project folder in path
project_root = str(Path(__file__).parent.parent.absolute())
if path[-1] != project_root: path.append(project_root)

# colored and detailed Python traceback
install(show_locals=True,width=Console().width,word_wrap=True)

# own modules
from modules.data_folder_types import *

parser = ArgumentParser(
    prog='print_history',
    description='Print the date and name of algorithms applied for the input folder')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input data folder',
    required=True)

args = parser.parse_args()

input_folder = AbstractDataFolder.instantiate(args.input)
input_folder.print_history()