#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
path.append(str(Path(__file__).parent.parent.absolute()))

from modules.data_folder_types import *

parser = ArgumentParser(
    prog='robustPolycube',
    description='https://github.com/fprotais/robustPolycube')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type labeling)',
    required=True)

parser.add_argument(
    '--elem-sizing',
    dest='element_sizing',
    metavar='FLOAT',
    help='element sizing: ratio compared to the input mesh edge size. smaller = more hexahedra',
    default='1.0')

parser.add_argument(
    '--keep-debug-files',
    action='store_true',
    dest='keep_debug_files',
    help='if the debug .geogram files should be kept')

parser.add_argument(
    '--view',
    action='store_true',
    dest='view_output',
    help='visualize the output at the end')

args = parser.parse_args()

root_folder = root()
if args.input in root_folder.collections_manager.collections_names():
    print('input is a collection -> batch mode')
    print('NOT IMPLEMENTED')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
input.rb_generate_deformation(args.keep_debug_files)
subfolder = input.rb_generate_quantization(args.element_sizing,args.keep_debug_files)

if args.view_output:
    hexmesh_folder = AbstractDataFolder.instantiate(subfolder)
    hexmesh_folder.view()