#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
path.append(str(Path(__file__).parent.parent.absolute()))

from modules.data_folder_types import *

parser = ArgumentParser(
    prog='volume_labeling',
    description='Compute the volume labeling (per cell facet) from the surface labeling (per surface triangle)')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type labeling)',
    required=True)

args = parser.parse_args()

root_folder = root()
if args.input in root_folder.collections_manager.collections_names():
    print('input is a collection -> batch mode')
    print('NOT IMPLEMENTED')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
input.volume_labeling()

# no --view option because there is no visualization mode/tool for volume labelings