#!/usr/bin/env python

from pathlib import Path
from argparse import ArgumentParser
from sys import path
from rich.console import Console
from rich.traceback import install

# Add root of HexMeshWorkshop project folder in path
project_root = str(Path(__file__).parent.parent.absolute())
if path[-1] != project_root: path.append(project_root)

# colored and detailed Python traceback
install(show_locals=True,width=Console().width,word_wrap=True)

# own modules
from modules.data_folder_types import *

parser = ArgumentParser(
    prog='write_glb',
    description='Export the labeled mesh as glTF 2.0 binary file')

parser.add_argument(
    '-i', '--input',
    dest='input',
    metavar='PATH',
    help='path to the input folder (type labeling)',
    required=True)

parser.add_argument(
    '--with-polycube',
    action='store_true',
    dest='with_polycube',
    help='export the polycube deformation as glTF animation')

args = parser.parse_args()

root_folder = root()
if args.input in root_folder.collections_manager.collections_names():
    print('input is a collection -> batch mode')
    print('NOT IMPLEMENTED')
    exit(0)

input = AbstractDataFolder.instantiate(Path(args.input))
if input.type() == 'tet_mesh':
    assert(args.with_polycube == False) # this option is only for 'labeling' input folders
    input.write_glb()
elif input.type() == 'labeling':
    input.write_glb(args.with_polycube)
elif input.type() == 'hex_mesh':
    assert(args.with_polycube == False) # this option is only for 'labeling' input folders
    input.write_glb()
else:
    logging.error(f"Invalid input folder type : '{input.type()}'")